name: test

on: [workflow_dispatch, push, pull_request]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes > build-output.txt
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv > test-output.txt
        id: test

      - name: Commit results
        run: |
          git config --local user.email "danieldimitrov2304@gmail.com"
          git config --local user.name "GitHub Action"
          git add build-output.txt test-output.txt
          git commit -m "Update build and test results" -a || echo "No changes to commit"
          git push https://${{ secrets.MY_PAT }}@github.com/DanielDimitrov5/ERC-20-Bridge.git
      
